% behavior_transitions.m - declared transition table of autonomy/behavior/state_machine.py
% GENERATED by scripts/export_matlab.py. UNTESTED IN MATLAB (no MATLAB installation available).
% Rows are in priority order: the first guard that fires wins. Transitions listed in
% dwell_guarded_from are de-escalations from those states and additionally require
% time_in_state >= behavior.min_dwell_s (config/autonomy.yaml). One Stateflow state per row of S,
% one transition per row of T; guards are the Python functions named in T.guard.

priority = int32([0 1 2 3 4 5 6 7 8 9 10 11 12 13])';
from_states = {'CRUISE;FOLLOW;CAUTION;AVOID'; 'EMERGENCY_BRAKE'; 'AVOID;CAUTION'; 'EMERGENCY_BRAKE'; 'STOPPED'; 'REVERSING'; 'STOPPED'; 'STOPPED'; 'CRUISE;FOLLOW;CAUTION'; 'AVOID'; 'CRUISE;FOLLOW'; 'CRUISE;CAUTION'; 'AVOID'; 'CAUTION;FOLLOW'};
to_state = {'EMERGENCY_BRAKE'; 'STOPPED'; 'STOPPED'; 'CAUTION'; 'REVERSING'; 'CAUTION'; 'AVOID'; 'CAUTION'; 'AVOID'; 'CAUTION'; 'CAUTION'; 'FOLLOW'; 'FOLLOW'; 'CRUISE'};
guard = {'g_emergency'; 'g_stopped'; 'g_planner_standstill'; 'g_eb_release'; 'g_boxed_in'; 'g_reverse_done'; 'g_stopped_to_avoid'; 'g_stopped_release'; 'g_avoid'; 'g_avoid_release'; 'g_caution'; 'g_follow'; 'g_follow'; 'g_release_to_cruise'};
guard_doc = {''; ''; ''; ''; ''; ''; ''; ''; 'threats other than a lead vehicle we are following, or the current plan itself being on a collision course (whichever object), escalate to AVOID'; ''; ''; ''; ''; ''};
dwell_guarded_from = {''; 'EMERGENCY_BRAKE'; ''; 'EMERGENCY_BRAKE'; 'STOPPED'; 'REVERSING'; 'STOPPED'; 'STOPPED'; ''; 'AVOID'; ''; 'CAUTION'; 'AVOID'; 'CAUTION;FOLLOW'};
T = table(priority, from_states, to_state, guard, guard_doc, dwell_guarded_from);

state = {'CRUISE'; 'FOLLOW'; 'CAUTION'; 'AVOID'; 'EMERGENCY_BRAKE'; 'STOPPED'; 'REVERSING'};
code = int32([0 1 2 3 4 5 6])';
severity = int32([0 1 2 3 5 4 4])';
speed_policy = {'desired speed; lateral avoidance allowed'; 'min(desired, lead speed + gap error / follow_time_gap_s); lateral avoidance allowed'; 'desired * caution_speed_factor; lateral avoidance allowed'; 'desired * avoid_speed_factor; lateral avoidance allowed'; 'target 0, force_stop: stop trajectories only'; 'desired * caution_speed_factor; lateral avoidance allowed (planner keeps searching)'; 'desired * caution_speed_factor; lateral avoidance and reversing candidates allowed'};
S = table(state, code, severity, speed_policy);

clear priority from_states to_state guard guard_doc dwell_guarded_from state code severity speed_policy
disp(T); disp(S);
