% buses.m - Simulink.Bus objects for the SIH26037 autonomy contracts.
% GENERATED by scripts/export_matlab.py from autonomy/core/types.py on 2026-09-06.
% UNTESTED IN MATLAB: no MATLAB installation was available when this file was produced.
% Run the script (R2016b+ for the script-local helper function) to create the bus objects
% in the base workspace:   >> buses
% Type mapping: float -> double, int -> int32, bool -> boolean, Enum -> int32 (codes below),
% Optional[float] -> double with NaN meaning None, Optional[int] -> int32 with -1 meaning None.
%
% Enumeration codes (int32):
%   BehaviorState: 0=CRUISE, 1=FOLLOW, 2=CAUTION, 3=AVOID, 4=EMERGENCY_BRAKE, 5=STOPPED, 6=REVERSING
%   RiskLevel: 0=NONE, 1=LOW, 2=MEDIUM, 3=HIGH, 4=CRITICAL
%   ObjectType: 0=PEDESTRIAN, 1=BICYCLE, 2=MOTORCYCLE, 3=AUTO_RICKSHAW, 4=CAR, 5=BUS, 6=TRUCK, 7=PUSHCART, 8=CATTLE, 9=UNKNOWN

% ---- VehicleState ----
elems = Simulink.BusElement.empty;
elems(end+1) = el('timestamp', 'double', 1, 'python: float');
elems(end+1) = el('x', 'double', 1, 'python: float');
elems(end+1) = el('y', 'double', 1, 'python: float');
elems(end+1) = el('yaw', 'double', 1, 'python: float');
elems(end+1) = el('longitudinal_velocity', 'double', 1, 'python: float');
elems(end+1) = el('lateral_velocity', 'double', 1, 'python: float');
elems(end+1) = el('yaw_rate', 'double', 1, 'python: float');
elems(end+1) = el('longitudinal_acceleration', 'double', 1, 'python: float');
elems(end+1) = el('steering_angle', 'double', 1, 'python: float');
VehicleState = Simulink.Bus;
VehicleState.Elements = elems;
VehicleState.Description = 'Generated from Python dataclass VehicleState';
assignin('base', 'VehicleState', VehicleState);

% ---- ControlCommand ----
%   skipped field source: type str is not carried on a bus (string / list / dict / tuple)
elems = Simulink.BusElement.empty;
elems(end+1) = el('timestamp', 'double', 1, 'python: float');
elems(end+1) = el('steering_angle', 'double', 1, 'python: float');
elems(end+1) = el('acceleration', 'double', 1, 'python: float');
elems(end+1) = el('brake', 'double', 1, 'python: float');
elems(end+1) = el('reverse', 'boolean', 1, 'python: bool');
ControlCommand = Simulink.Bus;
ControlCommand.Elements = elems;
ControlCommand.Description = 'Generated from Python dataclass ControlCommand';
assignin('base', 'ControlCommand', ControlCommand);

% ---- ObjectState ----
%   skipped field id: type str is not carried on a bus (string / list / dict / tuple)
elems = Simulink.BusElement.empty;
elems(end+1) = el('object_type', 'int32', 1, 'python: ObjectType (enum ObjectType, see code table)');
elems(end+1) = el('timestamp', 'double', 1, 'python: float');
elems(end+1) = el('x', 'double', 1, 'python: float');
elems(end+1) = el('y', 'double', 1, 'python: float');
elems(end+1) = el('vx', 'double', 1, 'python: float');
elems(end+1) = el('vy', 'double', 1, 'python: float');
elems(end+1) = el('heading', 'double', 1, 'python: float');
elems(end+1) = el('length', 'double', 1, 'python: float');
elems(end+1) = el('width', 'double', 1, 'python: float');
elems(end+1) = el('confidence', 'double', 1, 'python: float');
elems(end+1) = el('covariance', 'double', [2 2], 'python: ndarray');
ObjectState = Simulink.Bus;
ObjectState.Elements = elems;
ObjectState.Description = 'Generated from Python dataclass ObjectState';
assignin('base', 'ObjectState', ObjectState);

% ---- RiskSummary ----
%   skipped field assessments: type list is not carried on a bus (string / list / dict / tuple)
%   skipped field worst_object_id: type Optional is not carried on a bus (string / list / dict / tuple)
%   skipped field lead_object_id: type Optional is not carried on a bus (string / list / dict / tuple)
elems = Simulink.BusElement.empty;
elems(end+1) = el('max_level', 'int32', 1, 'python: RiskLevel (enum RiskLevel, see code table)');
elems(end+1) = el('max_score', 'double', 1, 'python: float');
elems(end+1) = el('min_ttc', 'double', 1, 'python: float');
elems(end+1) = el('min_predicted_distance', 'double', 1, 'python: float');
elems(end+1) = el('any_intersection', 'boolean', 1, 'python: bool');
elems(end+1) = el('lead_gap', 'double', 1, 'python: float');
elems(end+1) = el('lead_speed', 'double', 1, 'python: float');
elems(end+1) = el('min_ttc_current_speed', 'double', 1, 'python: float');
elems(end+1) = el('non_lead_max_level', 'int32', 1, 'python: RiskLevel (enum RiskLevel, see code table)');
elems(end+1) = el('non_lead_max_score', 'double', 1, 'python: float');
elems(end+1) = el('non_lead_any_intersection', 'boolean', 1, 'python: bool');
elems(end+1) = el('plan_min_ttc', 'double', 1, 'python: float');
elems(end+1) = el('plan_max_score', 'double', 1, 'python: float');
elems(end+1) = el('plan_max_level', 'int32', 1, 'python: RiskLevel (enum RiskLevel, see code table)');
elems(end+1) = el('plan_any_intersection', 'boolean', 1, 'python: bool');
elems(end+1) = el('plan_min_predicted_distance', 'double', 1, 'python: float');
RiskSummary = Simulink.Bus;
RiskSummary.Elements = elems;
RiskSummary.Description = 'Generated from Python dataclass RiskSummary';
assignin('base', 'RiskSummary', RiskSummary);

% ---- SpeedPolicy ----
elems = Simulink.BusElement.empty;
elems(end+1) = el('target_speed', 'double', 1, 'python: float');
elems(end+1) = el('allow_lateral_avoidance', 'boolean', 1, 'python: bool');
elems(end+1) = el('force_stop', 'boolean', 1, 'python: bool');
elems(end+1) = el('allow_reverse', 'boolean', 1, 'python: bool');
SpeedPolicy = Simulink.Bus;
SpeedPolicy.Elements = elems;
SpeedPolicy.Description = 'Generated from Python dataclass SpeedPolicy';
assignin('base', 'SpeedPolicy', SpeedPolicy);

% ---- BehaviorDecision ----
%   skipped field reason: type str is not carried on a bus (string / list / dict / tuple)
%   skipped field triggers: type dict is not carried on a bus (string / list / dict / tuple)
elems = Simulink.BusElement.empty;
elems(end+1) = el('timestamp', 'double', 1, 'python: float');
elems(end+1) = el('state', 'int32', 1, 'python: BehaviorState (enum BehaviorState, see code table)');
elems(end+1) = el('previous_state', 'int32', 1, 'python: BehaviorState (enum BehaviorState, see code table)');
elems(end+1) = el('speed_policy', 'Bus: SpeedPolicy', 1, 'python: SpeedPolicy');
elems(end+1) = el('time_in_state', 'double', 1, 'python: float');
BehaviorDecision = Simulink.Bus;
BehaviorDecision.Elements = elems;
BehaviorDecision.Description = 'Generated from Python dataclass BehaviorDecision';
assignin('base', 'BehaviorDecision', BehaviorDecision);

% ---- SimulationMetrics ----
%   skipped field behavior_state_durations: type dict is not carried on a bus (string / list / dict / tuple)
%   skipped field termination_reason: type str is not carried on a bus (string / list / dict / tuple)
elems = Simulink.BusElement.empty;
elems(end+1) = el('minimum_obstacle_clearance', 'double', 1, 'python: float');
elems(end+1) = el('collision_count', 'int32', 1, 'python: int');
elems(end+1) = el('scenario_completed', 'boolean', 1, 'python: bool');
elems(end+1) = el('time_to_completion', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('replanning_count', 'int32', 1, 'python: int');
elems(end+1) = el('plan_change_count', 'int32', 1, 'python: int');
elems(end+1) = el('planning_latency_mean_ms', 'double', 1, 'python: float');
elems(end+1) = el('planning_latency_max_ms', 'double', 1, 'python: float');
elems(end+1) = el('max_acceleration', 'double', 1, 'python: float');
elems(end+1) = el('max_deceleration', 'double', 1, 'python: float');
elems(end+1) = el('max_steering_rate', 'double', 1, 'python: float');
elems(end+1) = el('max_curvature', 'double', 1, 'python: float');
elems(end+1) = el('mean_abs_curvature', 'double', 1, 'python: float');
elems(end+1) = el('path_length', 'double', 1, 'python: float');
elems(end+1) = el('average_speed', 'double', 1, 'python: float');
elems(end+1) = el('emergency_brake_activations', 'int32', 1, 'python: int');
elems(end+1) = el('reverse_manoeuvres', 'int32', 1, 'python: int');
elems(end+1) = el('reverse_distance_m', 'double', 1, 'python: float');
elems(end+1) = el('minimum_ttc', 'double', 1, 'python: float');
elems(end+1) = el('behavior_transitions', 'int32', 1, 'python: int');
elems(end+1) = el('max_jerk', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('path_smoothness', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('scenario_success_rate', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('perception_latency_ms', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('prediction_error_m', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('tracking_position_error_m', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('tracking_velocity_error_mps', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('track_count_mean', 'double', 1, 'python: Optional (NaN when None)');
elems(end+1) = el('detections_total', 'int32', 1, 'python: int');
SimulationMetrics = Simulink.Bus;
SimulationMetrics.Elements = elems;
SimulationMetrics.Description = 'Generated from Python dataclass SimulationMetrics';
assignin('base', 'SimulationMetrics', SimulationMetrics);

clear elems

function e = el(name, dataType, dims, description)
% Build one Simulink.BusElement (script-local function, R2016b or newer).
e = Simulink.BusElement;
e.Name = name;
e.DataType = dataType;
e.Dimensions = dims;
e.Description = description;
end
