"""Export the behaviour FSM's declared TRANSITIONS table and state list for a Stateflow chart."""
from __future__ import annotations

import csv
import inspect
from pathlib import Path
from typing import Optional

from autonomy.behavior.state_machine import SEVERITY, TRANSITIONS, Guard
from autonomy.core.types import BehaviorState
from matlab_export.buses import enum_code, m_str

# Mirrors BehaviorStateMachine._policy; factor names are keys of config/autonomy.yaml: behavior.
SPEED_POLICY: dict[BehaviorState, str] = {
    BehaviorState.CRUISE: "desired speed; lateral avoidance allowed",
    BehaviorState.FOLLOW: "min(desired, lead speed + gap error / follow_time_gap_s); lateral avoidance allowed",
    BehaviorState.CAUTION: "desired * caution_speed_factor; lateral avoidance allowed",
    BehaviorState.AVOID: "desired * avoid_speed_factor; lateral avoidance allowed",
    BehaviorState.EMERGENCY_BRAKE: "target 0, force_stop: stop trajectories only",
    BehaviorState.STOPPED: "desired * caution_speed_factor; lateral avoidance allowed (planner keeps searching)",
    BehaviorState.REVERSING: "desired * caution_speed_factor; lateral avoidance and reversing candidates allowed",
}

TRANSITION_FIELDS = ["priority", "from_states", "to_state", "guard", "guard_doc", "dwell_guarded_from"]
STATE_FIELDS = ["state", "code", "severity", "speed_policy"]


def guard_doc(guard: Guard) -> str:
    """The guard's docstring, else its first block of consecutive `#` comment lines, else an empty string."""
    doc = inspect.getdoc(guard)
    if doc:
        return doc.splitlines()[0]
    block: list[str] = []
    for line in inspect.getsource(guard).splitlines()[1:]:
        stripped = line.strip()
        if stripped.startswith("#"):
            block.append(stripped.lstrip("# ").strip())
        elif block:
            break
    return " ".join(block)


def transition_rows() -> list[dict[str, str]]:
    rows = []
    for priority, (from_states, to_state, guard) in enumerate(TRANSITIONS):
        dwell = [s.value for s in from_states if SEVERITY[to_state] <= SEVERITY[s]]   # de-escalations wait min_dwell_s
        rows.append({
            "priority": str(priority),
            "from_states": ";".join(s.value for s in from_states),
            "to_state": to_state.value,
            "guard": guard.__name__,
            "guard_doc": guard_doc(guard),
            "dwell_guarded_from": ";".join(dwell),
        })
    return rows


def state_rows() -> list[dict[str, str]]:
    return [{"state": s.value, "code": str(enum_code(s)), "severity": str(SEVERITY[s]),
             "speed_policy": SPEED_POLICY[s]} for s in BehaviorState]


def write_csv(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def _cellstr(values: list[str]) -> str:
    return "{" + "; ".join(m_str(v) for v in values) + "}"


def render_transitions_m(rows: Optional[list[dict[str, str]]] = None) -> str:
    """A MATLAB script building table `T` (transitions, priority order) and `S` (states)."""
    rows = rows or transition_rows()
    states = state_rows()
    lines = [
        "% behavior_transitions.m - declared transition table of autonomy/behavior/state_machine.py",
        "% GENERATED by scripts/export_matlab.py. UNTESTED IN MATLAB (no MATLAB installation available).",
        "% Rows are in priority order: the first guard that fires wins. Transitions listed in",
        "% dwell_guarded_from are de-escalations from those states and additionally require",
        "% time_in_state >= behavior.min_dwell_s (config/autonomy.yaml). One Stateflow state per row of S,",
        "% one transition per row of T; guards are the Python functions named in T.guard.",
        "",
        f"priority = int32([{' '.join(r['priority'] for r in rows)}])';",
        f"from_states = {_cellstr([r['from_states'] for r in rows])};",
        f"to_state = {_cellstr([r['to_state'] for r in rows])};",
        f"guard = {_cellstr([r['guard'] for r in rows])};",
        f"guard_doc = {_cellstr([r['guard_doc'] for r in rows])};",
        f"dwell_guarded_from = {_cellstr([r['dwell_guarded_from'] for r in rows])};",
        "T = table(priority, from_states, to_state, guard, guard_doc, dwell_guarded_from);",
        "",
        f"state = {_cellstr([s['state'] for s in states])};",
        f"code = int32([{' '.join(s['code'] for s in states)}])';",
        f"severity = int32([{' '.join(s['severity'] for s in states)}])';",
        f"speed_policy = {_cellstr([s['speed_policy'] for s in states])};",
        "S = table(state, code, severity, speed_policy);",
        "",
        "clear priority from_states to_state guard guard_doc dwell_guarded_from state code severity speed_policy",
        "disp(T); disp(S);",
        "",
    ]
    return "\n".join(lines)
