"""Generate `buses.m`: Simulink.Bus definitions introspected from the dataclasses in autonomy/core/types.py.

Type mapping (Python -> MATLAB): float -> double, int -> int32, bool -> boolean,
Enum -> int32 (code table emitted as a comment), Optional[X] -> X with NaN /
-1 meaning "None", nested dataclass -> nested bus, 2x2 numpy covariance ->
double [2 2]. Strings, lists, dicts and tuples are not bus material and are
listed as skipped in a comment so nothing disappears silently.
"""
from __future__ import annotations

import dataclasses
import datetime as _dt
import types
import typing
from enum import Enum
from typing import Any, Optional

import numpy as np

from autonomy.core.types import (BehaviorDecision, BehaviorState, ControlCommand, ObjectState, ObjectType,
                                 RiskLevel, RiskSummary, SimulationMetrics, SpeedPolicy, VehicleState)

# Nested buses first so dependents can reference them.
BUS_CLASSES: tuple[type, ...] = (VehicleState, ControlCommand, ObjectState, RiskSummary, SpeedPolicy,
                                 BehaviorDecision, SimulationMetrics)
ENUMS: tuple[type[Enum], ...] = (BehaviorState, RiskLevel, ObjectType)
ARRAY_DIMS: dict[str, list[int]] = {"covariance": [2, 2]}   # numpy fields with a fixed, known shape


@dataclasses.dataclass
class BusElement:
    name: str
    data_type: str
    dims: list[int]
    description: str


@dataclasses.dataclass
class BusSpec:
    name: str
    elements: list[BusElement]
    skipped: list[tuple[str, str]]          # (field, reason)


def enum_code(member: Enum) -> int:
    """int-valued enums keep their value; string enums use their declaration index."""
    return int(member.value) if isinstance(member.value, int) else list(type(member)).index(member)


def _unwrap_optional(hint: Any) -> tuple[Any, bool]:
    origin = typing.get_origin(hint)
    if origin in (typing.Union, types.UnionType):
        args = [a for a in typing.get_args(hint) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
    return hint, False


def _type_name(hint: Any) -> str:
    return getattr(hint, "__name__", None) or str(hint).replace("typing.", "")


def map_field(f: dataclasses.Field, hint: Any, bus_names: set[str]) -> BusElement | tuple[str, str]:
    """Return a BusElement, or (field, reason) when the field cannot live on a bus."""
    inner, optional = _unwrap_optional(hint)
    none_note = ""
    if inner is float:
        dtype, none_note = "double", (" (NaN when None)" if optional else "")
    elif inner is int:
        dtype, none_note = "int32", (" (-1 when None)" if optional else "")
    elif inner is bool:
        dtype = "boolean"
    elif isinstance(inner, type) and issubclass(inner, Enum):
        dtype, none_note = "int32", f" (enum {inner.__name__}, see code table)"
    elif inner is np.ndarray and f.name in ARRAY_DIMS:
        dtype = "double"
    elif isinstance(inner, type) and dataclasses.is_dataclass(inner) and inner.__name__ in bus_names:
        dtype = f"Bus: {inner.__name__}"
    else:
        return f.name, f"type {_type_name(hint)} is not carried on a bus (string / list / dict / tuple)"
    return BusElement(f.name, dtype, ARRAY_DIMS.get(f.name, [1]), f"python: {_type_name(hint)}{none_note}")


def bus_specs() -> list[BusSpec]:
    names = {c.__name__ for c in BUS_CLASSES}
    specs = []
    for cls in BUS_CLASSES:
        hints = typing.get_type_hints(cls)
        elements: list[BusElement] = []
        skipped: list[tuple[str, str]] = []
        for f in dataclasses.fields(cls):
            mapped = map_field(f, hints[f.name], names)
            if isinstance(mapped, BusElement):
                elements.append(mapped)
            else:
                skipped.append(mapped)
        specs.append(BusSpec(cls.__name__, elements, skipped))
    return specs


def m_str(s: str) -> str:
    """Quote a string as a MATLAB char literal."""
    return "'" + s.replace("'", "''") + "'"


def render_buses_m(specs: Optional[list[BusSpec]] = None) -> str:
    specs = specs or bus_specs()
    out: list[str] = [
        "% buses.m - Simulink.Bus objects for the SIH26037 autonomy contracts.",
        f"% GENERATED by scripts/export_matlab.py from autonomy/core/types.py on {_dt.date.today().isoformat()}.",
        "% UNTESTED IN MATLAB: no MATLAB installation was available when this file was produced.",
        "% Run the script (R2016b+ for the script-local helper function) to create the bus objects",
        "% in the base workspace:   >> buses",
        "% Type mapping: float -> double, int -> int32, bool -> boolean, Enum -> int32 (codes below),",
        "% Optional[float] -> double with NaN meaning None, Optional[int] -> int32 with -1 meaning None.",
        "%",
        "% Enumeration codes (int32):",
    ]
    for enum in ENUMS:
        out.append(f"%   {enum.__name__}: " + ", ".join(f"{enum_code(m)}={m.name}" for m in enum))
    out.append("")
    for spec in specs:
        out.append(f"% ---- {spec.name} ----")
        for field, reason in spec.skipped:
            out.append(f"%   skipped field {field}: {reason}")
        out.append("elems = Simulink.BusElement.empty;")
        for e in spec.elements:
            dims = f"[{e.dims[0]} {e.dims[1]}]" if len(e.dims) == 2 else str(e.dims[0])
            out.append(f"elems(end+1) = el({m_str(e.name)}, {m_str(e.data_type)}, {dims}, {m_str(e.description)});")
        out.append(f"{spec.name} = Simulink.Bus;")
        out.append(f"{spec.name}.Elements = elems;")
        out.append(f"{spec.name}.Description = {m_str('Generated from Python dataclass ' + spec.name)};")
        out.append(f"assignin('base', {m_str(spec.name)}, {spec.name});")
        out.append("")
    out += [
        "clear elems",
        "",
        "function e = el(name, dataType, dims, description)",
        "% Build one Simulink.BusElement (script-local function, R2016b or newer).",
        "e = Simulink.BusElement;",
        "e.Name = name;",
        "e.DataType = dataType;",
        "e.Dimensions = dims;",
        "e.Description = description;",
        "end",
        "",
    ]
    return "\n".join(out)
